In [1]:
import pandas as pd
import datetime as dt

In [2]:
# 1. Create a DataFrame for the 201908-citibike-tripdata data. 

file_to_load = "201908-citibike-tripdata.csv"
nyc_citibike_df = pd.read_csv(file_to_load)
nyc_citibike_df.head(5)

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,393,2019-08-01 00:00:01.4680,2019-08-01 00:06:35.3780,531.0,Forsyth St & Broome St,40.718939,-73.992663,408.0,Market St & Cherry St,40.710762,-73.994004,35305,Subscriber,1996,2
1,627,2019-08-01 00:00:01.9290,2019-08-01 00:10:29.7840,274.0,Lafayette Ave & Fort Greene Pl,40.686919,-73.976682,3409.0,Bergen St & Smith St,40.686744,-73.990632,38822,Subscriber,1998,2
2,1132,2019-08-01 00:00:04.0480,2019-08-01 00:18:56.1650,2000.0,Front St & Washington St,40.702551,-73.989402,3388.0,President St & Henry St,40.682800,-73.999904,18373,Subscriber,1988,1
3,1780,2019-08-01 00:00:04.1630,2019-08-01 00:29:44.7940,479.0,9 Ave & W 45 St,40.760193,-73.991255,473.0,Rivington St & Chrystie St,40.721101,-73.991925,25002,Subscriber,1988,1
4,1517,2019-08-01 00:00:05.4580,2019-08-01 00:25:23.4550,3312.0,1 Ave & E 94 St,40.781721,-73.945940,3312.0,1 Ave & E 94 St,40.781721,-73.945940,31198,Subscriber,1965,2

In [3]:
# 2. Check the datatypes of your columns. 
nyc_citibike_df.dtypes

tripduration                 int64
starttime                   object
stoptime                    object
start station id           float64
start station name          object
start station latitude     float64
start station longitude    float64
end station id             float64
end station name            object
end station latitude       float64
end station longitude      float64
bikeid                       int64
usertype                    object
birth year                   int64
gender                       int64
dtype: object

In [4]:
# 3. Convert the 'tripduration' column to datetime datatype.
new_tripduration = nyc_citibike_df.tripduration
# print(new_tripduration)

new_tripduration_datetime = pd.to_datetime(new_tripduration, unit='m')
# print(new_tripduration_datetime)

# Add a new column for the converted trip duration
nyc_citibike_df['new_tripduration'] = new_tripduration_datetime

# Convert the numeric gender values to string values 
nyc_citibike_df['gender'].replace([0,1,2],['Unknown','Male','Female'],inplace=True)
nyc_citibike_df.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender,new_tripduration
0,393,2019-08-01 00:00:01.4680,2019-08-01 00:06:35.3780,531.0,Forsyth St & Broome St,40.718939,-73.992663,408.0,Market St & Cherry St,40.710762,-73.994004,35305,Subscriber,1996,Female,1970-01-01 06:33:00
1,627,2019-08-01 00:00:01.9290,2019-08-01 00:10:29.7840,274.0,Lafayette Ave & Fort Greene Pl,40.686919,-73.976682,3409.0,Bergen St & Smith St,40.686744,-73.990632,38822,Subscriber,1998,Female,1970-01-01 10:27:00
2,1132,2019-08-01 00:00:04.0480,2019-08-01 00:18:56.1650,2000.0,Front St & Washington St,40.702551,-73.989402,3388.0,President St & Henry St,40.682800,-73.999904,18373,Subscriber,1988,Male,1970-01-01 18:52:00
3,1780,2019-08-01 00:00:04.1630,2019-08-01 00:29:44.7940,479.0,9 Ave & W 45 St,40.760193,-73.991255,473.0,Rivington St & Chrystie St,40.721101,-73.991925,25002,Subscriber,1988,Male,1970-01-02 05:40:00
4,1517,2019-08-01 00:00:05.4580,2019-08-01 00:25:23.4550,3312.0,1 Ave & E 94 St,40.781721,-73.945940,3312.0,1 Ave & E 94 St,40.781721,-73.945940,31198,Subscriber,1965,Female,1970-01-02 01:17:00

In [5]:
# Remove old 'tripduration' column

nyc_citibike_df.drop(['tripduration'], axis=1).head(6)

,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender,new_tripduration
0,2019-08-01 00:00:01.4680,2019-08-01 00:06:35.3780,531.0,Forsyth St & Broome St,40.718939,-73.992663,408.0,Market St & Cherry St,40.710762,-73.994004,35305,Subscriber,1996,Female,1970-01-01 06:33:00
1,2019-08-01 00:00:01.9290,2019-08-01 00:10:29.7840,274.0,Lafayette Ave & Fort Greene Pl,40.686919,-73.976682,3409.0,Bergen St & Smith St,40.686744,-73.990632,38822,Subscriber,1998,Female,1970-01-01 10:27:00
2,2019-08-01 00:00:04.0480,2019-08-01 00:18:56.1650,2000.0,Front St & Washington St,40.702551,-73.989402,3388.0,President St & Henry St,40.682800,-73.999904,18373,Subscriber,1988,Male,1970-01-01 18:52:00
3,2019-08-01 00:00:04.1630,2019-08-01 00:29:44.7940,479.0,9 Ave & W 45 St,40.760193,-73.991255,473.0,Rivington St & Chrystie St,40.721101,-73.991925,25002,Subscriber,1988,Male,1970-01-02 05:40:00
4,2019-08-01 00:00:05.4580,2019-08-01 00:25:23.4550,3312.0,1 Ave & E 94 St,40.781721,-73.945940,3312.0,1 Ave & E 94 St,40.781721,-73.945940,31198,Subscriber,1965,Female,1970-01-02 01:17:00
5,2019-08-01 00:00:11.8060,2019-08-01 00:10:43.9590,173.0,Broadway & W 49 St,40.760683,-73.984527,3707.0,Lexington Ave & E 26 St,40.741459,-73.983293,21628,Subscriber,1998,Male,1970-01-01 10:32:00

In [6]:
###### rearrange column

In [7]:
# 4. Check the datatypes of your columns. 
nyc_citibike_df.dtypes

tripduration                        int64
starttime                          object
stoptime                           object
start station id                  float64
start station name                 object
start station latitude            float64
start station longitude           float64
end station id                    float64
end station name                   object
end station latitude              float64
end station longitude             float64
bikeid                              int64
usertype                           object
birth year                          int64
gender                             object
new_tripduration           datetime64[ns]
dtype: object

In [8]:
##### Reorder the columns

nyc_citibike_df2=nyc_citibike_df.reindex(columns= ['new_tripduration', 'starttime', 'start station id','start station name', 'start station latitude', 'start station longitude','end station id', 'end station name','end station latitude','end station longitude','bikeid', 'usertype','birth year', 'gender'   ])

#new_tripduration_datetime = pd.to_datetime(new_tripduration, unit='m')
nyc_citibike_df2.head(6)

,new_tripduration,starttime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,1970-01-01 06:33:00,2019-08-01 00:00:01.4680,531.0,Forsyth St & Broome St,40.718939,-73.992663,408.0,Market St & Cherry St,40.710762,-73.994004,35305,Subscriber,1996,Female
1,1970-01-01 10:27:00,2019-08-01 00:00:01.9290,274.0,Lafayette Ave & Fort Greene Pl,40.686919,-73.976682,3409.0,Bergen St & Smith St,40.686744,-73.990632,38822,Subscriber,1998,Female
2,1970-01-01 18:52:00,2019-08-01 00:00:04.0480,2000.0,Front St & Washington St,40.702551,-73.989402,3388.0,President St & Henry St,40.682800,-73.999904,18373,Subscriber,1988,Male
3,1970-01-02 05:40:00,2019-08-01 00:00:04.1630,479.0,9 Ave & W 45 St,40.760193,-73.991255,473.0,Rivington St & Chrystie St,40.721101,-73.991925,25002,Subscriber,1988,Male
4,1970-01-02 01:17:00,2019-08-01 00:00:05.4580,3312.0,1 Ave & E 94 St,40.781721,-73.945940,3312.0,1 Ave & E 94 St,40.781721,-73.945940,31198,Subscriber,1965,Female
5,1970-01-01 10:32:00,2019-08-01 00:00:11.8060,173.0,Broadway & W 49 St,40.760683,-73.984527,3707.0,Lexington Ave & E 26 St,40.741459,-73.983293,21628,Subscriber,1998,Male

In [10]:
# 5. Export the Dataframe as a new CSV file without the index.

nyc_citibike_df.to_csv("nyc_citibike_3.csv", index = False)